eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging.level.io.github.solomkinmv.glossary: trace

security.oauth2.resource.jwk.key-set-uri: http://localhost:8000/auth/realms/glossary/protocol/openid-connect/certs

spring.rabbitmq.host: localhost