server:
  port: 8086

endpoints:
  prometheus:
    enabled: true

spring:
  cloud.stream.bindings:
    input:
      destination: learned-words
      group: stats

    output:
      destination: learned-words

  data.mongodb:
#    authentication-database: admin
    database: stats
    host: mongo-0.mongo
#    password: pswrd
#    username: mongo_user

queue.name: learned-words.stats
