server:
  port: 8085

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  cloud.stream.bindings:
    output:
      destination: learned-words

hystrix.command.tts-service.execution.isolation.thread.timeoutInMilliseconds: 4000

ribbon:
  eager-load:
    enabled: true
    clients: tts-service

  ReadTimeout: 2500
  ConnectTimeout: 300