server:
  port: 8085

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

hystrix.command.tts-service.execution.isolation.thread.timeoutInMilliseconds: 4000